"""2015053101

Revision ID: 805619f9e569
Revises: e24b49e07e07
Create Date: 2016-05-31 08:16:35.073985

"""

# revision identifiers, used by Alembic.
revision = '805619f9e569'
down_revision = 'e24b49e07e07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
