"""2015053102

Revision ID: d7f6b320fa51
Revises: 805619f9e569
Create Date: 2016-05-31 09:02:50.831760

"""

# revision identifiers, used by Alembic.
revision = 'd7f6b320fa51'
down_revision = '805619f9e569'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
