"""2015053002

Revision ID: e24b49e07e07
Revises: 803611626331
Create Date: 2016-05-30 23:27:09.809949

"""

# revision identifiers, used by Alembic.
revision = 'e24b49e07e07'
down_revision = '803611626331'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
